/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTabelaRouteImport } from './routes/_authenticated/tabela'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedRelatoriosAdminRouteImport } from './routes/_authenticated/relatorios-admin'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRegularizacaoRouteImport } from './routes/_authenticated/regularizacao'
import { Route as AuthenticatedRegistrosRouteImport } from './routes/_authenticated/registros'
import { Route as AuthenticatedPortaisRouteImport } from './routes/_authenticated/portais'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedLoteamentosRouteImport } from './routes/_authenticated/loteamentos'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedEdificiosRouteImport } from './routes/_authenticated/edificios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCondominiosRouteImport } from './routes/_authenticated/condominios'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCarteirasRouteImport } from './routes/_authenticated/carteiras'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedAcessoNegadoRouteImport } from './routes/_authenticated/acesso-negado'
import { Route as AuthenticatedSegurancaIndexRouteImport } from './routes/_authenticated/seguranca.index'
import { Route as AuthenticatedRelatoriosAdminIndexRouteImport } from './routes/_authenticated/relatorios-admin.index'
import { Route as AuthenticatedRegistrosIndexRouteImport } from './routes/_authenticated/registros.index'
import { Route as AuthenticatedPortaisIndexRouteImport } from './routes/_authenticated/portais.index'
import { Route as AuthenticatedImportacoesIndexRouteImport } from './routes/_authenticated/importacoes.index'
import { Route as AuthenticatedImoveisIndexRouteImport } from './routes/_authenticated/imoveis.index'
import { Route as AuthenticatedCarteirasIndexRouteImport } from './routes/_authenticated/carteiras.index'
import { Route as AuthenticatedSegurancaSessoesRouteImport } from './routes/_authenticated/seguranca.sessoes'
import { Route as AuthenticatedSegurancaPermissoesRouteImport } from './routes/_authenticated/seguranca.permissoes'
import { Route as AuthenticatedSegurancaAlertasRouteImport } from './routes/_authenticated/seguranca.alertas'
import { Route as AuthenticatedSegurancaAcessosRouteImport } from './routes/_authenticated/seguranca.acessos'
import { Route as AuthenticatedRelatoriosAdminRankingsRouteImport } from './routes/_authenticated/relatorios-admin.rankings'
import { Route as AuthenticatedRelatoriosAdminImoveisRouteImport } from './routes/_authenticated/relatorios-admin.imoveis'
import { Route as AuthenticatedRelatoriosAdminImobiliariasRouteImport } from './routes/_authenticated/relatorios-admin.imobiliarias'
import { Route as AuthenticatedRelatoriosAdminExportacoesRouteImport } from './routes/_authenticated/relatorios-admin.exportacoes'
import { Route as AuthenticatedRelatoriosAdminCorretoresRouteImport } from './routes/_authenticated/relatorios-admin.corretores'
import { Route as AuthenticatedRelatoriosAdminAtividadeRouteImport } from './routes/_authenticated/relatorios-admin.atividade'
import { Route as AuthenticatedRegistrosNovoRouteImport } from './routes/_authenticated/registros.novo'
import { Route as AuthenticatedRegistrosIdRouteImport } from './routes/_authenticated/registros.$id'
import { Route as AuthenticatedImportacoesMvBrokerRouteImport } from './routes/_authenticated/importacoes.mv-broker'
import { Route as AuthenticatedImportacoesImoveisRouteImport } from './routes/_authenticated/importacoes.imoveis'
import { Route as AuthenticatedImportacoesEdificiosRouteImport } from './routes/_authenticated/importacoes.edificios'
import { Route as AuthenticatedImportacoesCondominiosRouteImport } from './routes/_authenticated/importacoes.condominios'
import { Route as AuthenticatedImoveisNovoRouteImport } from './routes/_authenticated/imoveis.novo'
import { Route as AuthenticatedImoveisExportacaoRouteImport } from './routes/_authenticated/imoveis.exportacao'
import { Route as AuthenticatedConfiguracoesOpcoesRouteImport } from './routes/_authenticated/configuracoes.opcoes'
import { Route as AuthenticatedConfiguracoesNotificacoesRouteImport } from './routes/_authenticated/configuracoes.notificacoes'
import { Route as AuthenticatedCarteirasIdRouteImport } from './routes/_authenticated/carteiras.$id'
import { Route as AuthenticatedAssinaturasIdRouteImport } from './routes/_authenticated/assinaturas.$id'
import { Route as ApiPublicFeedSlugRouteImport } from './routes/api/public/feed/$slug'
import { Route as AuthenticatedRegistrosIdEditarRouteImport } from './routes/_authenticated/registros.$id.editar'
import { Route as AuthenticatedImoveisIdEditarRouteImport } from './routes/_authenticated/imoveis.$id.editar'
import { Route as AuthenticatedEmpreendimentosTipoIdRouteImport } from './routes/_authenticated/empreendimentos.$tipo.$id'
import { Route as ApiPublicPortalPortalSlugRouteImport } from './routes/api/public/portal/$portal/$slug'
import { Route as ApiPublicFeedGeralIdRouteImport } from './routes/api/public/feed/geral.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTabelaRoute = AuthenticatedTabelaRouteImport.update({
  id: '/tabela',
  path: '/tabela',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosAdminRoute =
  AuthenticatedRelatoriosAdminRouteImport.update({
    id: '/relatorios-admin',
    path: '/relatorios-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegularizacaoRoute =
  AuthenticatedRegularizacaoRouteImport.update({
    id: '/regularizacao',
    path: '/regularizacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistrosRoute = AuthenticatedRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortaisRoute = AuthenticatedPortaisRouteImport.update({
  id: '/portais',
  path: '/portais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoteamentosRoute =
  AuthenticatedLoteamentosRouteImport.update({
    id: '/loteamentos',
    path: '/loteamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEdificiosRoute = AuthenticatedEdificiosRouteImport.update({
  id: '/edificios',
  path: '/edificios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCondominiosRoute =
  AuthenticatedCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarteirasRoute = AuthenticatedCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcessoNegadoRoute =
  AuthenticatedAcessoNegadoRouteImport.update({
    id: '/acesso-negado',
    path: '/acesso-negado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSegurancaIndexRoute =
  AuthenticatedSegurancaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSegurancaRoute,
  } as any)
const AuthenticatedRelatoriosAdminIndexRoute =
  AuthenticatedRelatoriosAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRegistrosIndexRoute =
  AuthenticatedRegistrosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedPortaisIndexRoute =
  AuthenticatedPortaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortaisRoute,
  } as any)
const AuthenticatedImportacoesIndexRoute =
  AuthenticatedImportacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImportacoesRoute,
  } as any)
const AuthenticatedImoveisIndexRoute =
  AuthenticatedImoveisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedCarteirasIndexRoute =
  AuthenticatedCarteirasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarteirasRoute,
  } as any)
const AuthenticatedSegurancaSessoesRoute =
  AuthenticatedSegurancaSessoesRouteImport.update({
    id: '/sessoes',
    path: '/sessoes',
    getParentRoute: () => AuthenticatedSegurancaRoute,
  } as any)
const AuthenticatedSegurancaPermissoesRoute =
  AuthenticatedSegurancaPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedSegurancaRoute,
  } as any)
const AuthenticatedSegurancaAlertasRoute =
  AuthenticatedSegurancaAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedSegurancaRoute,
  } as any)
const AuthenticatedSegurancaAcessosRoute =
  AuthenticatedSegurancaAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedSegurancaRoute,
  } as any)
const AuthenticatedRelatoriosAdminRankingsRoute =
  AuthenticatedRelatoriosAdminRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRelatoriosAdminImoveisRoute =
  AuthenticatedRelatoriosAdminImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRelatoriosAdminImobiliariasRoute =
  AuthenticatedRelatoriosAdminImobiliariasRouteImport.update({
    id: '/imobiliarias',
    path: '/imobiliarias',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRelatoriosAdminExportacoesRoute =
  AuthenticatedRelatoriosAdminExportacoesRouteImport.update({
    id: '/exportacoes',
    path: '/exportacoes',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRelatoriosAdminCorretoresRoute =
  AuthenticatedRelatoriosAdminCorretoresRouteImport.update({
    id: '/corretores',
    path: '/corretores',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRelatoriosAdminAtividadeRoute =
  AuthenticatedRelatoriosAdminAtividadeRouteImport.update({
    id: '/atividade',
    path: '/atividade',
    getParentRoute: () => AuthenticatedRelatoriosAdminRoute,
  } as any)
const AuthenticatedRegistrosNovoRoute =
  AuthenticatedRegistrosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedRegistrosIdRoute =
  AuthenticatedRegistrosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedImportacoesMvBrokerRoute =
  AuthenticatedImportacoesMvBrokerRouteImport.update({
    id: '/mv-broker',
    path: '/mv-broker',
    getParentRoute: () => AuthenticatedImportacoesRoute,
  } as any)
const AuthenticatedImportacoesImoveisRoute =
  AuthenticatedImportacoesImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedImportacoesRoute,
  } as any)
const AuthenticatedImportacoesEdificiosRoute =
  AuthenticatedImportacoesEdificiosRouteImport.update({
    id: '/edificios',
    path: '/edificios',
    getParentRoute: () => AuthenticatedImportacoesRoute,
  } as any)
const AuthenticatedImportacoesCondominiosRoute =
  AuthenticatedImportacoesCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedImportacoesRoute,
  } as any)
const AuthenticatedImoveisNovoRoute =
  AuthenticatedImoveisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedImoveisExportacaoRoute =
  AuthenticatedImoveisExportacaoRouteImport.update({
    id: '/exportacao',
    path: '/exportacao',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedConfiguracoesOpcoesRoute =
  AuthenticatedConfiguracoesOpcoesRouteImport.update({
    id: '/opcoes',
    path: '/opcoes',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesNotificacoesRoute =
  AuthenticatedConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedCarteirasIdRoute =
  AuthenticatedCarteirasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCarteirasRoute,
  } as any)
const AuthenticatedAssinaturasIdRoute =
  AuthenticatedAssinaturasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssinaturasRoute,
  } as any)
const ApiPublicFeedSlugRoute = ApiPublicFeedSlugRouteImport.update({
  id: '/api/public/feed/$slug',
  path: '/api/public/feed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistrosIdEditarRoute =
  AuthenticatedRegistrosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedRegistrosIdRoute,
  } as any)
const AuthenticatedImoveisIdEditarRoute =
  AuthenticatedImoveisIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedEmpreendimentosTipoIdRoute =
  AuthenticatedEmpreendimentosTipoIdRouteImport.update({
    id: '/empreendimentos/$tipo/$id',
    path: '/empreendimentos/$tipo/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPortalPortalSlugRoute =
  ApiPublicPortalPortalSlugRouteImport.update({
    id: '/api/public/portal/$portal/$slug',
    path: '/api/public/portal/$portal/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedGeralIdRoute = ApiPublicFeedGeralIdRouteImport.update({
  id: '/api/public/feed/geral/$id',
  path: '/api/public/feed/geral/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acesso-negado': typeof AuthenticatedAcessoNegadoRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/carteiras': typeof AuthenticatedCarteirasRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/condominios': typeof AuthenticatedCondominiosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edificios': typeof AuthenticatedEdificiosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/importacoes': typeof AuthenticatedImportacoesRouteWithChildren
  '/loteamentos': typeof AuthenticatedLoteamentosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/portais': typeof AuthenticatedPortaisRouteWithChildren
  '/registros': typeof AuthenticatedRegistrosRouteWithChildren
  '/regularizacao': typeof AuthenticatedRegularizacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-admin': typeof AuthenticatedRelatoriosAdminRouteWithChildren
  '/seguranca': typeof AuthenticatedSegurancaRouteWithChildren
  '/tabela': typeof AuthenticatedTabelaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assinaturas/$id': typeof AuthenticatedAssinaturasIdRoute
  '/carteiras/$id': typeof AuthenticatedCarteirasIdRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/imoveis/exportacao': typeof AuthenticatedImoveisExportacaoRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/importacoes/condominios': typeof AuthenticatedImportacoesCondominiosRoute
  '/importacoes/edificios': typeof AuthenticatedImportacoesEdificiosRoute
  '/importacoes/imoveis': typeof AuthenticatedImportacoesImoveisRoute
  '/importacoes/mv-broker': typeof AuthenticatedImportacoesMvBrokerRoute
  '/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/relatorios-admin/atividade': typeof AuthenticatedRelatoriosAdminAtividadeRoute
  '/relatorios-admin/corretores': typeof AuthenticatedRelatoriosAdminCorretoresRoute
  '/relatorios-admin/exportacoes': typeof AuthenticatedRelatoriosAdminExportacoesRoute
  '/relatorios-admin/imobiliarias': typeof AuthenticatedRelatoriosAdminImobiliariasRoute
  '/relatorios-admin/imoveis': typeof AuthenticatedRelatoriosAdminImoveisRoute
  '/relatorios-admin/rankings': typeof AuthenticatedRelatoriosAdminRankingsRoute
  '/seguranca/acessos': typeof AuthenticatedSegurancaAcessosRoute
  '/seguranca/alertas': typeof AuthenticatedSegurancaAlertasRoute
  '/seguranca/permissoes': typeof AuthenticatedSegurancaPermissoesRoute
  '/seguranca/sessoes': typeof AuthenticatedSegurancaSessoesRoute
  '/carteiras/': typeof AuthenticatedCarteirasIndexRoute
  '/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/importacoes/': typeof AuthenticatedImportacoesIndexRoute
  '/portais/': typeof AuthenticatedPortaisIndexRoute
  '/registros/': typeof AuthenticatedRegistrosIndexRoute
  '/relatorios-admin/': typeof AuthenticatedRelatoriosAdminIndexRoute
  '/seguranca/': typeof AuthenticatedSegurancaIndexRoute
  '/empreendimentos/$tipo/$id': typeof AuthenticatedEmpreendimentosTipoIdRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
  '/api/public/feed/$slug': typeof ApiPublicFeedSlugRoute
  '/api/public/feed/geral/$id': typeof ApiPublicFeedGeralIdRoute
  '/api/public/portal/$portal/$slug': typeof ApiPublicPortalPortalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acesso-negado': typeof AuthenticatedAcessoNegadoRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/condominios': typeof AuthenticatedCondominiosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edificios': typeof AuthenticatedEdificiosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/loteamentos': typeof AuthenticatedLoteamentosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/regularizacao': typeof AuthenticatedRegularizacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tabela': typeof AuthenticatedTabelaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assinaturas/$id': typeof AuthenticatedAssinaturasIdRoute
  '/carteiras/$id': typeof AuthenticatedCarteirasIdRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/imoveis/exportacao': typeof AuthenticatedImoveisExportacaoRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/importacoes/condominios': typeof AuthenticatedImportacoesCondominiosRoute
  '/importacoes/edificios': typeof AuthenticatedImportacoesEdificiosRoute
  '/importacoes/imoveis': typeof AuthenticatedImportacoesImoveisRoute
  '/importacoes/mv-broker': typeof AuthenticatedImportacoesMvBrokerRoute
  '/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/relatorios-admin/atividade': typeof AuthenticatedRelatoriosAdminAtividadeRoute
  '/relatorios-admin/corretores': typeof AuthenticatedRelatoriosAdminCorretoresRoute
  '/relatorios-admin/exportacoes': typeof AuthenticatedRelatoriosAdminExportacoesRoute
  '/relatorios-admin/imobiliarias': typeof AuthenticatedRelatoriosAdminImobiliariasRoute
  '/relatorios-admin/imoveis': typeof AuthenticatedRelatoriosAdminImoveisRoute
  '/relatorios-admin/rankings': typeof AuthenticatedRelatoriosAdminRankingsRoute
  '/seguranca/acessos': typeof AuthenticatedSegurancaAcessosRoute
  '/seguranca/alertas': typeof AuthenticatedSegurancaAlertasRoute
  '/seguranca/permissoes': typeof AuthenticatedSegurancaPermissoesRoute
  '/seguranca/sessoes': typeof AuthenticatedSegurancaSessoesRoute
  '/carteiras': typeof AuthenticatedCarteirasIndexRoute
  '/imoveis': typeof AuthenticatedImoveisIndexRoute
  '/importacoes': typeof AuthenticatedImportacoesIndexRoute
  '/portais': typeof AuthenticatedPortaisIndexRoute
  '/registros': typeof AuthenticatedRegistrosIndexRoute
  '/relatorios-admin': typeof AuthenticatedRelatoriosAdminIndexRoute
  '/seguranca': typeof AuthenticatedSegurancaIndexRoute
  '/empreendimentos/$tipo/$id': typeof AuthenticatedEmpreendimentosTipoIdRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
  '/api/public/feed/$slug': typeof ApiPublicFeedSlugRoute
  '/api/public/feed/geral/$id': typeof ApiPublicFeedGeralIdRoute
  '/api/public/portal/$portal/$slug': typeof ApiPublicPortalPortalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/acesso-negado': typeof AuthenticatedAcessoNegadoRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRouteWithChildren
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/carteiras': typeof AuthenticatedCarteirasRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/condominios': typeof AuthenticatedCondominiosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/edificios': typeof AuthenticatedEdificiosRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRouteWithChildren
  '/_authenticated/loteamentos': typeof AuthenticatedLoteamentosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/portais': typeof AuthenticatedPortaisRouteWithChildren
  '/_authenticated/registros': typeof AuthenticatedRegistrosRouteWithChildren
  '/_authenticated/regularizacao': typeof AuthenticatedRegularizacaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/relatorios-admin': typeof AuthenticatedRelatoriosAdminRouteWithChildren
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRouteWithChildren
  '/_authenticated/tabela': typeof AuthenticatedTabelaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/assinaturas/$id': typeof AuthenticatedAssinaturasIdRoute
  '/_authenticated/carteiras/$id': typeof AuthenticatedCarteirasIdRoute
  '/_authenticated/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/_authenticated/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/_authenticated/imoveis/exportacao': typeof AuthenticatedImoveisExportacaoRoute
  '/_authenticated/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/_authenticated/importacoes/condominios': typeof AuthenticatedImportacoesCondominiosRoute
  '/_authenticated/importacoes/edificios': typeof AuthenticatedImportacoesEdificiosRoute
  '/_authenticated/importacoes/imoveis': typeof AuthenticatedImportacoesImoveisRoute
  '/_authenticated/importacoes/mv-broker': typeof AuthenticatedImportacoesMvBrokerRoute
  '/_authenticated/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/_authenticated/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/_authenticated/relatorios-admin/atividade': typeof AuthenticatedRelatoriosAdminAtividadeRoute
  '/_authenticated/relatorios-admin/corretores': typeof AuthenticatedRelatoriosAdminCorretoresRoute
  '/_authenticated/relatorios-admin/exportacoes': typeof AuthenticatedRelatoriosAdminExportacoesRoute
  '/_authenticated/relatorios-admin/imobiliarias': typeof AuthenticatedRelatoriosAdminImobiliariasRoute
  '/_authenticated/relatorios-admin/imoveis': typeof AuthenticatedRelatoriosAdminImoveisRoute
  '/_authenticated/relatorios-admin/rankings': typeof AuthenticatedRelatoriosAdminRankingsRoute
  '/_authenticated/seguranca/acessos': typeof AuthenticatedSegurancaAcessosRoute
  '/_authenticated/seguranca/alertas': typeof AuthenticatedSegurancaAlertasRoute
  '/_authenticated/seguranca/permissoes': typeof AuthenticatedSegurancaPermissoesRoute
  '/_authenticated/seguranca/sessoes': typeof AuthenticatedSegurancaSessoesRoute
  '/_authenticated/carteiras/': typeof AuthenticatedCarteirasIndexRoute
  '/_authenticated/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/_authenticated/importacoes/': typeof AuthenticatedImportacoesIndexRoute
  '/_authenticated/portais/': typeof AuthenticatedPortaisIndexRoute
  '/_authenticated/registros/': typeof AuthenticatedRegistrosIndexRoute
  '/_authenticated/relatorios-admin/': typeof AuthenticatedRelatoriosAdminIndexRoute
  '/_authenticated/seguranca/': typeof AuthenticatedSegurancaIndexRoute
  '/_authenticated/empreendimentos/$tipo/$id': typeof AuthenticatedEmpreendimentosTipoIdRoute
  '/_authenticated/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/_authenticated/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
  '/api/public/feed/$slug': typeof ApiPublicFeedSlugRoute
  '/api/public/feed/geral/$id': typeof ApiPublicFeedGeralIdRoute
  '/api/public/portal/$portal/$slug': typeof ApiPublicPortalPortalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/acesso-negado'
    | '/assinaturas'
    | '/auditoria'
    | '/biblioteca'
    | '/carteiras'
    | '/clientes'
    | '/condominios'
    | '/configuracoes'
    | '/dashboard'
    | '/edificios'
    | '/favoritos'
    | '/imoveis'
    | '/importacoes'
    | '/loteamentos'
    | '/notificacoes'
    | '/oportunidades'
    | '/pagamentos'
    | '/perfil'
    | '/planos'
    | '/portais'
    | '/registros'
    | '/regularizacao'
    | '/relatorios'
    | '/relatorios-admin'
    | '/seguranca'
    | '/tabela'
    | '/usuarios'
    | '/assinaturas/$id'
    | '/carteiras/$id'
    | '/configuracoes/notificacoes'
    | '/configuracoes/opcoes'
    | '/imoveis/exportacao'
    | '/imoveis/novo'
    | '/importacoes/condominios'
    | '/importacoes/edificios'
    | '/importacoes/imoveis'
    | '/importacoes/mv-broker'
    | '/registros/$id'
    | '/registros/novo'
    | '/relatorios-admin/atividade'
    | '/relatorios-admin/corretores'
    | '/relatorios-admin/exportacoes'
    | '/relatorios-admin/imobiliarias'
    | '/relatorios-admin/imoveis'
    | '/relatorios-admin/rankings'
    | '/seguranca/acessos'
    | '/seguranca/alertas'
    | '/seguranca/permissoes'
    | '/seguranca/sessoes'
    | '/carteiras/'
    | '/imoveis/'
    | '/importacoes/'
    | '/portais/'
    | '/registros/'
    | '/relatorios-admin/'
    | '/seguranca/'
    | '/empreendimentos/$tipo/$id'
    | '/imoveis/$id/editar'
    | '/registros/$id/editar'
    | '/api/public/feed/$slug'
    | '/api/public/feed/geral/$id'
    | '/api/public/portal/$portal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/acesso-negado'
    | '/assinaturas'
    | '/auditoria'
    | '/biblioteca'
    | '/clientes'
    | '/condominios'
    | '/configuracoes'
    | '/dashboard'
    | '/edificios'
    | '/favoritos'
    | '/loteamentos'
    | '/notificacoes'
    | '/oportunidades'
    | '/pagamentos'
    | '/perfil'
    | '/planos'
    | '/regularizacao'
    | '/relatorios'
    | '/tabela'
    | '/usuarios'
    | '/assinaturas/$id'
    | '/carteiras/$id'
    | '/configuracoes/notificacoes'
    | '/configuracoes/opcoes'
    | '/imoveis/exportacao'
    | '/imoveis/novo'
    | '/importacoes/condominios'
    | '/importacoes/edificios'
    | '/importacoes/imoveis'
    | '/importacoes/mv-broker'
    | '/registros/$id'
    | '/registros/novo'
    | '/relatorios-admin/atividade'
    | '/relatorios-admin/corretores'
    | '/relatorios-admin/exportacoes'
    | '/relatorios-admin/imobiliarias'
    | '/relatorios-admin/imoveis'
    | '/relatorios-admin/rankings'
    | '/seguranca/acessos'
    | '/seguranca/alertas'
    | '/seguranca/permissoes'
    | '/seguranca/sessoes'
    | '/carteiras'
    | '/imoveis'
    | '/importacoes'
    | '/portais'
    | '/registros'
    | '/relatorios-admin'
    | '/seguranca'
    | '/empreendimentos/$tipo/$id'
    | '/imoveis/$id/editar'
    | '/registros/$id/editar'
    | '/api/public/feed/$slug'
    | '/api/public/feed/geral/$id'
    | '/api/public/portal/$portal/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/_authenticated/acesso-negado'
    | '/_authenticated/assinaturas'
    | '/_authenticated/auditoria'
    | '/_authenticated/biblioteca'
    | '/_authenticated/carteiras'
    | '/_authenticated/clientes'
    | '/_authenticated/condominios'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/edificios'
    | '/_authenticated/favoritos'
    | '/_authenticated/imoveis'
    | '/_authenticated/importacoes'
    | '/_authenticated/loteamentos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/oportunidades'
    | '/_authenticated/pagamentos'
    | '/_authenticated/perfil'
    | '/_authenticated/planos'
    | '/_authenticated/portais'
    | '/_authenticated/registros'
    | '/_authenticated/regularizacao'
    | '/_authenticated/relatorios'
    | '/_authenticated/relatorios-admin'
    | '/_authenticated/seguranca'
    | '/_authenticated/tabela'
    | '/_authenticated/usuarios'
    | '/_authenticated/assinaturas/$id'
    | '/_authenticated/carteiras/$id'
    | '/_authenticated/configuracoes/notificacoes'
    | '/_authenticated/configuracoes/opcoes'
    | '/_authenticated/imoveis/exportacao'
    | '/_authenticated/imoveis/novo'
    | '/_authenticated/importacoes/condominios'
    | '/_authenticated/importacoes/edificios'
    | '/_authenticated/importacoes/imoveis'
    | '/_authenticated/importacoes/mv-broker'
    | '/_authenticated/registros/$id'
    | '/_authenticated/registros/novo'
    | '/_authenticated/relatorios-admin/atividade'
    | '/_authenticated/relatorios-admin/corretores'
    | '/_authenticated/relatorios-admin/exportacoes'
    | '/_authenticated/relatorios-admin/imobiliarias'
    | '/_authenticated/relatorios-admin/imoveis'
    | '/_authenticated/relatorios-admin/rankings'
    | '/_authenticated/seguranca/acessos'
    | '/_authenticated/seguranca/alertas'
    | '/_authenticated/seguranca/permissoes'
    | '/_authenticated/seguranca/sessoes'
    | '/_authenticated/carteiras/'
    | '/_authenticated/imoveis/'
    | '/_authenticated/importacoes/'
    | '/_authenticated/portais/'
    | '/_authenticated/registros/'
    | '/_authenticated/relatorios-admin/'
    | '/_authenticated/seguranca/'
    | '/_authenticated/empreendimentos/$tipo/$id'
    | '/_authenticated/imoveis/$id/editar'
    | '/_authenticated/registros/$id/editar'
    | '/api/public/feed/$slug'
    | '/api/public/feed/geral/$id'
    | '/api/public/portal/$portal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicFeedSlugRoute: typeof ApiPublicFeedSlugRoute
  ApiPublicFeedGeralIdRoute: typeof ApiPublicFeedGeralIdRoute
  ApiPublicPortalPortalSlugRoute: typeof ApiPublicPortalPortalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabela': {
      id: '/_authenticated/tabela'
      path: '/tabela'
      fullPath: '/tabela'
      preLoaderRoute: typeof AuthenticatedTabelaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-admin': {
      id: '/_authenticated/relatorios-admin'
      path: '/relatorios-admin'
      fullPath: '/relatorios-admin'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/regularizacao': {
      id: '/_authenticated/regularizacao'
      path: '/regularizacao'
      fullPath: '/regularizacao'
      preLoaderRoute: typeof AuthenticatedRegularizacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registros': {
      id: '/_authenticated/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AuthenticatedRegistrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portais': {
      id: '/_authenticated/portais'
      path: '/portais'
      fullPath: '/portais'
      preLoaderRoute: typeof AuthenticatedPortaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loteamentos': {
      id: '/_authenticated/loteamentos'
      path: '/loteamentos'
      fullPath: '/loteamentos'
      preLoaderRoute: typeof AuthenticatedLoteamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edificios': {
      id: '/_authenticated/edificios'
      path: '/edificios'
      fullPath: '/edificios'
      preLoaderRoute: typeof AuthenticatedEdificiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/condominios': {
      id: '/_authenticated/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof AuthenticatedCondominiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carteiras': {
      id: '/_authenticated/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof AuthenticatedCarteirasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acesso-negado': {
      id: '/_authenticated/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AuthenticatedAcessoNegadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seguranca/': {
      id: '/_authenticated/seguranca/'
      path: '/'
      fullPath: '/seguranca/'
      preLoaderRoute: typeof AuthenticatedSegurancaIndexRouteImport
      parentRoute: typeof AuthenticatedSegurancaRoute
    }
    '/_authenticated/relatorios-admin/': {
      id: '/_authenticated/relatorios-admin/'
      path: '/'
      fullPath: '/relatorios-admin/'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/registros/': {
      id: '/_authenticated/registros/'
      path: '/'
      fullPath: '/registros/'
      preLoaderRoute: typeof AuthenticatedRegistrosIndexRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/portais/': {
      id: '/_authenticated/portais/'
      path: '/'
      fullPath: '/portais/'
      preLoaderRoute: typeof AuthenticatedPortaisIndexRouteImport
      parentRoute: typeof AuthenticatedPortaisRoute
    }
    '/_authenticated/importacoes/': {
      id: '/_authenticated/importacoes/'
      path: '/'
      fullPath: '/importacoes/'
      preLoaderRoute: typeof AuthenticatedImportacoesIndexRouteImport
      parentRoute: typeof AuthenticatedImportacoesRoute
    }
    '/_authenticated/imoveis/': {
      id: '/_authenticated/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AuthenticatedImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/carteiras/': {
      id: '/_authenticated/carteiras/'
      path: '/'
      fullPath: '/carteiras/'
      preLoaderRoute: typeof AuthenticatedCarteirasIndexRouteImport
      parentRoute: typeof AuthenticatedCarteirasRoute
    }
    '/_authenticated/seguranca/sessoes': {
      id: '/_authenticated/seguranca/sessoes'
      path: '/sessoes'
      fullPath: '/seguranca/sessoes'
      preLoaderRoute: typeof AuthenticatedSegurancaSessoesRouteImport
      parentRoute: typeof AuthenticatedSegurancaRoute
    }
    '/_authenticated/seguranca/permissoes': {
      id: '/_authenticated/seguranca/permissoes'
      path: '/permissoes'
      fullPath: '/seguranca/permissoes'
      preLoaderRoute: typeof AuthenticatedSegurancaPermissoesRouteImport
      parentRoute: typeof AuthenticatedSegurancaRoute
    }
    '/_authenticated/seguranca/alertas': {
      id: '/_authenticated/seguranca/alertas'
      path: '/alertas'
      fullPath: '/seguranca/alertas'
      preLoaderRoute: typeof AuthenticatedSegurancaAlertasRouteImport
      parentRoute: typeof AuthenticatedSegurancaRoute
    }
    '/_authenticated/seguranca/acessos': {
      id: '/_authenticated/seguranca/acessos'
      path: '/acessos'
      fullPath: '/seguranca/acessos'
      preLoaderRoute: typeof AuthenticatedSegurancaAcessosRouteImport
      parentRoute: typeof AuthenticatedSegurancaRoute
    }
    '/_authenticated/relatorios-admin/rankings': {
      id: '/_authenticated/relatorios-admin/rankings'
      path: '/rankings'
      fullPath: '/relatorios-admin/rankings'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminRankingsRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/relatorios-admin/imoveis': {
      id: '/_authenticated/relatorios-admin/imoveis'
      path: '/imoveis'
      fullPath: '/relatorios-admin/imoveis'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminImoveisRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/relatorios-admin/imobiliarias': {
      id: '/_authenticated/relatorios-admin/imobiliarias'
      path: '/imobiliarias'
      fullPath: '/relatorios-admin/imobiliarias'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminImobiliariasRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/relatorios-admin/exportacoes': {
      id: '/_authenticated/relatorios-admin/exportacoes'
      path: '/exportacoes'
      fullPath: '/relatorios-admin/exportacoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminExportacoesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/relatorios-admin/corretores': {
      id: '/_authenticated/relatorios-admin/corretores'
      path: '/corretores'
      fullPath: '/relatorios-admin/corretores'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminCorretoresRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/relatorios-admin/atividade': {
      id: '/_authenticated/relatorios-admin/atividade'
      path: '/atividade'
      fullPath: '/relatorios-admin/atividade'
      preLoaderRoute: typeof AuthenticatedRelatoriosAdminAtividadeRouteImport
      parentRoute: typeof AuthenticatedRelatoriosAdminRoute
    }
    '/_authenticated/registros/novo': {
      id: '/_authenticated/registros/novo'
      path: '/novo'
      fullPath: '/registros/novo'
      preLoaderRoute: typeof AuthenticatedRegistrosNovoRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/registros/$id': {
      id: '/_authenticated/registros/$id'
      path: '/$id'
      fullPath: '/registros/$id'
      preLoaderRoute: typeof AuthenticatedRegistrosIdRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/importacoes/mv-broker': {
      id: '/_authenticated/importacoes/mv-broker'
      path: '/mv-broker'
      fullPath: '/importacoes/mv-broker'
      preLoaderRoute: typeof AuthenticatedImportacoesMvBrokerRouteImport
      parentRoute: typeof AuthenticatedImportacoesRoute
    }
    '/_authenticated/importacoes/imoveis': {
      id: '/_authenticated/importacoes/imoveis'
      path: '/imoveis'
      fullPath: '/importacoes/imoveis'
      preLoaderRoute: typeof AuthenticatedImportacoesImoveisRouteImport
      parentRoute: typeof AuthenticatedImportacoesRoute
    }
    '/_authenticated/importacoes/edificios': {
      id: '/_authenticated/importacoes/edificios'
      path: '/edificios'
      fullPath: '/importacoes/edificios'
      preLoaderRoute: typeof AuthenticatedImportacoesEdificiosRouteImport
      parentRoute: typeof AuthenticatedImportacoesRoute
    }
    '/_authenticated/importacoes/condominios': {
      id: '/_authenticated/importacoes/condominios'
      path: '/condominios'
      fullPath: '/importacoes/condominios'
      preLoaderRoute: typeof AuthenticatedImportacoesCondominiosRouteImport
      parentRoute: typeof AuthenticatedImportacoesRoute
    }
    '/_authenticated/imoveis/novo': {
      id: '/_authenticated/imoveis/novo'
      path: '/novo'
      fullPath: '/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/imoveis/exportacao': {
      id: '/_authenticated/imoveis/exportacao'
      path: '/exportacao'
      fullPath: '/imoveis/exportacao'
      preLoaderRoute: typeof AuthenticatedImoveisExportacaoRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/configuracoes/opcoes': {
      id: '/_authenticated/configuracoes/opcoes'
      path: '/opcoes'
      fullPath: '/configuracoes/opcoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOpcoesRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/notificacoes': {
      id: '/_authenticated/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/carteiras/$id': {
      id: '/_authenticated/carteiras/$id'
      path: '/$id'
      fullPath: '/carteiras/$id'
      preLoaderRoute: typeof AuthenticatedCarteirasIdRouteImport
      parentRoute: typeof AuthenticatedCarteirasRoute
    }
    '/_authenticated/assinaturas/$id': {
      id: '/_authenticated/assinaturas/$id'
      path: '/$id'
      fullPath: '/assinaturas/$id'
      preLoaderRoute: typeof AuthenticatedAssinaturasIdRouteImport
      parentRoute: typeof AuthenticatedAssinaturasRoute
    }
    '/api/public/feed/$slug': {
      id: '/api/public/feed/$slug'
      path: '/api/public/feed/$slug'
      fullPath: '/api/public/feed/$slug'
      preLoaderRoute: typeof ApiPublicFeedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registros/$id/editar': {
      id: '/_authenticated/registros/$id/editar'
      path: '/editar'
      fullPath: '/registros/$id/editar'
      preLoaderRoute: typeof AuthenticatedRegistrosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRegistrosIdRoute
    }
    '/_authenticated/imoveis/$id/editar': {
      id: '/_authenticated/imoveis/$id/editar'
      path: '/$id/editar'
      fullPath: '/imoveis/$id/editar'
      preLoaderRoute: typeof AuthenticatedImoveisIdEditarRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/empreendimentos/$tipo/$id': {
      id: '/_authenticated/empreendimentos/$tipo/$id'
      path: '/empreendimentos/$tipo/$id'
      fullPath: '/empreendimentos/$tipo/$id'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosTipoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/portal/$portal/$slug': {
      id: '/api/public/portal/$portal/$slug'
      path: '/api/public/portal/$portal/$slug'
      fullPath: '/api/public/portal/$portal/$slug'
      preLoaderRoute: typeof ApiPublicPortalPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed/geral/$id': {
      id: '/api/public/feed/geral/$id'
      path: '/api/public/feed/geral/$id'
      fullPath: '/api/public/feed/geral/$id'
      preLoaderRoute: typeof ApiPublicFeedGeralIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAssinaturasRouteChildren {
  AuthenticatedAssinaturasIdRoute: typeof AuthenticatedAssinaturasIdRoute
}

const AuthenticatedAssinaturasRouteChildren: AuthenticatedAssinaturasRouteChildren =
  {
    AuthenticatedAssinaturasIdRoute: AuthenticatedAssinaturasIdRoute,
  }

const AuthenticatedAssinaturasRouteWithChildren =
  AuthenticatedAssinaturasRoute._addFileChildren(
    AuthenticatedAssinaturasRouteChildren,
  )

interface AuthenticatedCarteirasRouteChildren {
  AuthenticatedCarteirasIdRoute: typeof AuthenticatedCarteirasIdRoute
  AuthenticatedCarteirasIndexRoute: typeof AuthenticatedCarteirasIndexRoute
}

const AuthenticatedCarteirasRouteChildren: AuthenticatedCarteirasRouteChildren =
  {
    AuthenticatedCarteirasIdRoute: AuthenticatedCarteirasIdRoute,
    AuthenticatedCarteirasIndexRoute: AuthenticatedCarteirasIndexRoute,
  }

const AuthenticatedCarteirasRouteWithChildren =
  AuthenticatedCarteirasRoute._addFileChildren(
    AuthenticatedCarteirasRouteChildren,
  )

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesNotificacoesRoute: typeof AuthenticatedConfiguracoesNotificacoesRoute
  AuthenticatedConfiguracoesOpcoesRoute: typeof AuthenticatedConfiguracoesOpcoesRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesNotificacoesRoute:
      AuthenticatedConfiguracoesNotificacoesRoute,
    AuthenticatedConfiguracoesOpcoesRoute:
      AuthenticatedConfiguracoesOpcoesRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedImoveisRouteChildren {
  AuthenticatedImoveisExportacaoRoute: typeof AuthenticatedImoveisExportacaoRoute
  AuthenticatedImoveisNovoRoute: typeof AuthenticatedImoveisNovoRoute
  AuthenticatedImoveisIndexRoute: typeof AuthenticatedImoveisIndexRoute
  AuthenticatedImoveisIdEditarRoute: typeof AuthenticatedImoveisIdEditarRoute
}

const AuthenticatedImoveisRouteChildren: AuthenticatedImoveisRouteChildren = {
  AuthenticatedImoveisExportacaoRoute: AuthenticatedImoveisExportacaoRoute,
  AuthenticatedImoveisNovoRoute: AuthenticatedImoveisNovoRoute,
  AuthenticatedImoveisIndexRoute: AuthenticatedImoveisIndexRoute,
  AuthenticatedImoveisIdEditarRoute: AuthenticatedImoveisIdEditarRoute,
}

const AuthenticatedImoveisRouteWithChildren =
  AuthenticatedImoveisRoute._addFileChildren(AuthenticatedImoveisRouteChildren)

interface AuthenticatedImportacoesRouteChildren {
  AuthenticatedImportacoesCondominiosRoute: typeof AuthenticatedImportacoesCondominiosRoute
  AuthenticatedImportacoesEdificiosRoute: typeof AuthenticatedImportacoesEdificiosRoute
  AuthenticatedImportacoesImoveisRoute: typeof AuthenticatedImportacoesImoveisRoute
  AuthenticatedImportacoesMvBrokerRoute: typeof AuthenticatedImportacoesMvBrokerRoute
  AuthenticatedImportacoesIndexRoute: typeof AuthenticatedImportacoesIndexRoute
}

const AuthenticatedImportacoesRouteChildren: AuthenticatedImportacoesRouteChildren =
  {
    AuthenticatedImportacoesCondominiosRoute:
      AuthenticatedImportacoesCondominiosRoute,
    AuthenticatedImportacoesEdificiosRoute:
      AuthenticatedImportacoesEdificiosRoute,
    AuthenticatedImportacoesImoveisRoute: AuthenticatedImportacoesImoveisRoute,
    AuthenticatedImportacoesMvBrokerRoute:
      AuthenticatedImportacoesMvBrokerRoute,
    AuthenticatedImportacoesIndexRoute: AuthenticatedImportacoesIndexRoute,
  }

const AuthenticatedImportacoesRouteWithChildren =
  AuthenticatedImportacoesRoute._addFileChildren(
    AuthenticatedImportacoesRouteChildren,
  )

interface AuthenticatedPortaisRouteChildren {
  AuthenticatedPortaisIndexRoute: typeof AuthenticatedPortaisIndexRoute
}

const AuthenticatedPortaisRouteChildren: AuthenticatedPortaisRouteChildren = {
  AuthenticatedPortaisIndexRoute: AuthenticatedPortaisIndexRoute,
}

const AuthenticatedPortaisRouteWithChildren =
  AuthenticatedPortaisRoute._addFileChildren(AuthenticatedPortaisRouteChildren)

interface AuthenticatedRegistrosIdRouteChildren {
  AuthenticatedRegistrosIdEditarRoute: typeof AuthenticatedRegistrosIdEditarRoute
}

const AuthenticatedRegistrosIdRouteChildren: AuthenticatedRegistrosIdRouteChildren =
  {
    AuthenticatedRegistrosIdEditarRoute: AuthenticatedRegistrosIdEditarRoute,
  }

const AuthenticatedRegistrosIdRouteWithChildren =
  AuthenticatedRegistrosIdRoute._addFileChildren(
    AuthenticatedRegistrosIdRouteChildren,
  )

interface AuthenticatedRegistrosRouteChildren {
  AuthenticatedRegistrosIdRoute: typeof AuthenticatedRegistrosIdRouteWithChildren
  AuthenticatedRegistrosNovoRoute: typeof AuthenticatedRegistrosNovoRoute
  AuthenticatedRegistrosIndexRoute: typeof AuthenticatedRegistrosIndexRoute
}

const AuthenticatedRegistrosRouteChildren: AuthenticatedRegistrosRouteChildren =
  {
    AuthenticatedRegistrosIdRoute: AuthenticatedRegistrosIdRouteWithChildren,
    AuthenticatedRegistrosNovoRoute: AuthenticatedRegistrosNovoRoute,
    AuthenticatedRegistrosIndexRoute: AuthenticatedRegistrosIndexRoute,
  }

const AuthenticatedRegistrosRouteWithChildren =
  AuthenticatedRegistrosRoute._addFileChildren(
    AuthenticatedRegistrosRouteChildren,
  )

interface AuthenticatedRelatoriosAdminRouteChildren {
  AuthenticatedRelatoriosAdminAtividadeRoute: typeof AuthenticatedRelatoriosAdminAtividadeRoute
  AuthenticatedRelatoriosAdminCorretoresRoute: typeof AuthenticatedRelatoriosAdminCorretoresRoute
  AuthenticatedRelatoriosAdminExportacoesRoute: typeof AuthenticatedRelatoriosAdminExportacoesRoute
  AuthenticatedRelatoriosAdminImobiliariasRoute: typeof AuthenticatedRelatoriosAdminImobiliariasRoute
  AuthenticatedRelatoriosAdminImoveisRoute: typeof AuthenticatedRelatoriosAdminImoveisRoute
  AuthenticatedRelatoriosAdminRankingsRoute: typeof AuthenticatedRelatoriosAdminRankingsRoute
  AuthenticatedRelatoriosAdminIndexRoute: typeof AuthenticatedRelatoriosAdminIndexRoute
}

const AuthenticatedRelatoriosAdminRouteChildren: AuthenticatedRelatoriosAdminRouteChildren =
  {
    AuthenticatedRelatoriosAdminAtividadeRoute:
      AuthenticatedRelatoriosAdminAtividadeRoute,
    AuthenticatedRelatoriosAdminCorretoresRoute:
      AuthenticatedRelatoriosAdminCorretoresRoute,
    AuthenticatedRelatoriosAdminExportacoesRoute:
      AuthenticatedRelatoriosAdminExportacoesRoute,
    AuthenticatedRelatoriosAdminImobiliariasRoute:
      AuthenticatedRelatoriosAdminImobiliariasRoute,
    AuthenticatedRelatoriosAdminImoveisRoute:
      AuthenticatedRelatoriosAdminImoveisRoute,
    AuthenticatedRelatoriosAdminRankingsRoute:
      AuthenticatedRelatoriosAdminRankingsRoute,
    AuthenticatedRelatoriosAdminIndexRoute:
      AuthenticatedRelatoriosAdminIndexRoute,
  }

const AuthenticatedRelatoriosAdminRouteWithChildren =
  AuthenticatedRelatoriosAdminRoute._addFileChildren(
    AuthenticatedRelatoriosAdminRouteChildren,
  )

interface AuthenticatedSegurancaRouteChildren {
  AuthenticatedSegurancaAcessosRoute: typeof AuthenticatedSegurancaAcessosRoute
  AuthenticatedSegurancaAlertasRoute: typeof AuthenticatedSegurancaAlertasRoute
  AuthenticatedSegurancaPermissoesRoute: typeof AuthenticatedSegurancaPermissoesRoute
  AuthenticatedSegurancaSessoesRoute: typeof AuthenticatedSegurancaSessoesRoute
  AuthenticatedSegurancaIndexRoute: typeof AuthenticatedSegurancaIndexRoute
}

const AuthenticatedSegurancaRouteChildren: AuthenticatedSegurancaRouteChildren =
  {
    AuthenticatedSegurancaAcessosRoute: AuthenticatedSegurancaAcessosRoute,
    AuthenticatedSegurancaAlertasRoute: AuthenticatedSegurancaAlertasRoute,
    AuthenticatedSegurancaPermissoesRoute:
      AuthenticatedSegurancaPermissoesRoute,
    AuthenticatedSegurancaSessoesRoute: AuthenticatedSegurancaSessoesRoute,
    AuthenticatedSegurancaIndexRoute: AuthenticatedSegurancaIndexRoute,
  }

const AuthenticatedSegurancaRouteWithChildren =
  AuthenticatedSegurancaRoute._addFileChildren(
    AuthenticatedSegurancaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcessoNegadoRoute: typeof AuthenticatedAcessoNegadoRoute
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRouteWithChildren
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCarteirasRoute: typeof AuthenticatedCarteirasRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCondominiosRoute: typeof AuthenticatedCondominiosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEdificiosRoute: typeof AuthenticatedEdificiosRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRouteWithChildren
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRouteWithChildren
  AuthenticatedLoteamentosRoute: typeof AuthenticatedLoteamentosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPortaisRoute: typeof AuthenticatedPortaisRouteWithChildren
  AuthenticatedRegistrosRoute: typeof AuthenticatedRegistrosRouteWithChildren
  AuthenticatedRegularizacaoRoute: typeof AuthenticatedRegularizacaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRelatoriosAdminRoute: typeof AuthenticatedRelatoriosAdminRouteWithChildren
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRouteWithChildren
  AuthenticatedTabelaRoute: typeof AuthenticatedTabelaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedEmpreendimentosTipoIdRoute: typeof AuthenticatedEmpreendimentosTipoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcessoNegadoRoute: AuthenticatedAcessoNegadoRoute,
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRouteWithChildren,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCarteirasRoute: AuthenticatedCarteirasRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCondominiosRoute: AuthenticatedCondominiosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEdificiosRoute: AuthenticatedEdificiosRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRouteWithChildren,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRouteWithChildren,
  AuthenticatedLoteamentosRoute: AuthenticatedLoteamentosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPortaisRoute: AuthenticatedPortaisRouteWithChildren,
  AuthenticatedRegistrosRoute: AuthenticatedRegistrosRouteWithChildren,
  AuthenticatedRegularizacaoRoute: AuthenticatedRegularizacaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRelatoriosAdminRoute:
    AuthenticatedRelatoriosAdminRouteWithChildren,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRouteWithChildren,
  AuthenticatedTabelaRoute: AuthenticatedTabelaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedEmpreendimentosTipoIdRoute:
    AuthenticatedEmpreendimentosTipoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicFeedSlugRoute: ApiPublicFeedSlugRoute,
  ApiPublicFeedGeralIdRoute: ApiPublicFeedGeralIdRoute,
  ApiPublicPortalPortalSlugRoute: ApiPublicPortalPortalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
