/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRegistrosRouteImport } from './routes/_authenticated/registros'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedImobiliariasRouteImport } from './routes/_authenticated/imobiliarias'
import { Route as AuthenticatedExportacoesRouteImport } from './routes/_authenticated/exportacoes'
import { Route as AuthenticatedEmpreendimentosRouteImport } from './routes/_authenticated/empreendimentos'
import { Route as AuthenticatedEdificiosRouteImport } from './routes/_authenticated/edificios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCondominiosRouteImport } from './routes/_authenticated/condominios'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedRegistrosIndexRouteImport } from './routes/_authenticated/registros.index'
import { Route as AuthenticatedImoveisIndexRouteImport } from './routes/_authenticated/imoveis.index'
import { Route as AuthenticatedRegistrosNovoRouteImport } from './routes/_authenticated/registros.novo'
import { Route as AuthenticatedRegistrosIdRouteImport } from './routes/_authenticated/registros.$id'
import { Route as AuthenticatedImoveisNovoRouteImport } from './routes/_authenticated/imoveis.novo'
import { Route as AuthenticatedConfiguracoesOpcoesRouteImport } from './routes/_authenticated/configuracoes.opcoes'
import { Route as AuthenticatedRegistrosIdEditarRouteImport } from './routes/_authenticated/registros.$id.editar'
import { Route as AuthenticatedImoveisIdEditarRouteImport } from './routes/_authenticated/imoveis.$id.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrosRoute = AuthenticatedRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImobiliariasRoute =
  AuthenticatedImobiliariasRouteImport.update({
    id: '/imobiliarias',
    path: '/imobiliarias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportacoesRoute =
  AuthenticatedExportacoesRouteImport.update({
    id: '/exportacoes',
    path: '/exportacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpreendimentosRoute =
  AuthenticatedEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEdificiosRoute = AuthenticatedEdificiosRouteImport.update({
  id: '/edificios',
  path: '/edificios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCondominiosRoute =
  AuthenticatedCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrosIndexRoute =
  AuthenticatedRegistrosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedImoveisIndexRoute =
  AuthenticatedImoveisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedRegistrosNovoRoute =
  AuthenticatedRegistrosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedRegistrosIdRoute =
  AuthenticatedRegistrosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRegistrosRoute,
  } as any)
const AuthenticatedImoveisNovoRoute =
  AuthenticatedImoveisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)
const AuthenticatedConfiguracoesOpcoesRoute =
  AuthenticatedConfiguracoesOpcoesRouteImport.update({
    id: '/opcoes',
    path: '/opcoes',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedRegistrosIdEditarRoute =
  AuthenticatedRegistrosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedRegistrosIdRoute,
  } as any)
const AuthenticatedImoveisIdEditarRoute =
  AuthenticatedImoveisIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedImoveisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/condominios': typeof AuthenticatedCondominiosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edificios': typeof AuthenticatedEdificiosRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/exportacoes': typeof AuthenticatedExportacoesRoute
  '/imobiliarias': typeof AuthenticatedImobiliariasRoute
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registros': typeof AuthenticatedRegistrosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/registros/': typeof AuthenticatedRegistrosIndexRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/condominios': typeof AuthenticatedCondominiosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edificios': typeof AuthenticatedEdificiosRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/exportacoes': typeof AuthenticatedExportacoesRoute
  '/imobiliarias': typeof AuthenticatedImobiliariasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/imoveis': typeof AuthenticatedImoveisIndexRoute
  '/registros': typeof AuthenticatedRegistrosIndexRoute
  '/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/condominios': typeof AuthenticatedCondominiosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/edificios': typeof AuthenticatedEdificiosRoute
  '/_authenticated/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/_authenticated/exportacoes': typeof AuthenticatedExportacoesRoute
  '/_authenticated/imobiliarias': typeof AuthenticatedImobiliariasRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/registros': typeof AuthenticatedRegistrosRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/configuracoes/opcoes': typeof AuthenticatedConfiguracoesOpcoesRoute
  '/_authenticated/imoveis/novo': typeof AuthenticatedImoveisNovoRoute
  '/_authenticated/registros/$id': typeof AuthenticatedRegistrosIdRouteWithChildren
  '/_authenticated/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/_authenticated/imoveis/': typeof AuthenticatedImoveisIndexRoute
  '/_authenticated/registros/': typeof AuthenticatedRegistrosIndexRoute
  '/_authenticated/imoveis/$id/editar': typeof AuthenticatedImoveisIdEditarRoute
  '/_authenticated/registros/$id/editar': typeof AuthenticatedRegistrosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/biblioteca'
    | '/clientes'
    | '/condominios'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/edificios'
    | '/empreendimentos'
    | '/exportacoes'
    | '/imobiliarias'
    | '/imoveis'
    | '/perfil'
    | '/registros'
    | '/relatorios'
    | '/usuarios'
    | '/configuracoes/opcoes'
    | '/imoveis/novo'
    | '/registros/$id'
    | '/registros/novo'
    | '/imoveis/'
    | '/registros/'
    | '/imoveis/$id/editar'
    | '/registros/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/biblioteca'
    | '/clientes'
    | '/condominios'
    | '/configuracoes'
    | '/corretores'
    | '/dashboard'
    | '/edificios'
    | '/empreendimentos'
    | '/exportacoes'
    | '/imobiliarias'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/configuracoes/opcoes'
    | '/imoveis/novo'
    | '/registros/$id'
    | '/registros/novo'
    | '/imoveis'
    | '/registros'
    | '/imoveis/$id/editar'
    | '/registros/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditoria'
    | '/_authenticated/biblioteca'
    | '/_authenticated/clientes'
    | '/_authenticated/condominios'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corretores'
    | '/_authenticated/dashboard'
    | '/_authenticated/edificios'
    | '/_authenticated/empreendimentos'
    | '/_authenticated/exportacoes'
    | '/_authenticated/imobiliarias'
    | '/_authenticated/imoveis'
    | '/_authenticated/perfil'
    | '/_authenticated/registros'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/configuracoes/opcoes'
    | '/_authenticated/imoveis/novo'
    | '/_authenticated/registros/$id'
    | '/_authenticated/registros/novo'
    | '/_authenticated/imoveis/'
    | '/_authenticated/registros/'
    | '/_authenticated/imoveis/$id/editar'
    | '/_authenticated/registros/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registros': {
      id: '/_authenticated/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AuthenticatedRegistrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imobiliarias': {
      id: '/_authenticated/imobiliarias'
      path: '/imobiliarias'
      fullPath: '/imobiliarias'
      preLoaderRoute: typeof AuthenticatedImobiliariasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exportacoes': {
      id: '/_authenticated/exportacoes'
      path: '/exportacoes'
      fullPath: '/exportacoes'
      preLoaderRoute: typeof AuthenticatedExportacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empreendimentos': {
      id: '/_authenticated/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edificios': {
      id: '/_authenticated/edificios'
      path: '/edificios'
      fullPath: '/edificios'
      preLoaderRoute: typeof AuthenticatedEdificiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/condominios': {
      id: '/_authenticated/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof AuthenticatedCondominiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registros/': {
      id: '/_authenticated/registros/'
      path: '/'
      fullPath: '/registros/'
      preLoaderRoute: typeof AuthenticatedRegistrosIndexRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/imoveis/': {
      id: '/_authenticated/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof AuthenticatedImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/registros/novo': {
      id: '/_authenticated/registros/novo'
      path: '/novo'
      fullPath: '/registros/novo'
      preLoaderRoute: typeof AuthenticatedRegistrosNovoRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/registros/$id': {
      id: '/_authenticated/registros/$id'
      path: '/$id'
      fullPath: '/registros/$id'
      preLoaderRoute: typeof AuthenticatedRegistrosIdRouteImport
      parentRoute: typeof AuthenticatedRegistrosRoute
    }
    '/_authenticated/imoveis/novo': {
      id: '/_authenticated/imoveis/novo'
      path: '/novo'
      fullPath: '/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
    '/_authenticated/configuracoes/opcoes': {
      id: '/_authenticated/configuracoes/opcoes'
      path: '/opcoes'
      fullPath: '/configuracoes/opcoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOpcoesRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/registros/$id/editar': {
      id: '/_authenticated/registros/$id/editar'
      path: '/editar'
      fullPath: '/registros/$id/editar'
      preLoaderRoute: typeof AuthenticatedRegistrosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRegistrosIdRoute
    }
    '/_authenticated/imoveis/$id/editar': {
      id: '/_authenticated/imoveis/$id/editar'
      path: '/$id/editar'
      fullPath: '/imoveis/$id/editar'
      preLoaderRoute: typeof AuthenticatedImoveisIdEditarRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesOpcoesRoute: typeof AuthenticatedConfiguracoesOpcoesRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesOpcoesRoute:
      AuthenticatedConfiguracoesOpcoesRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedImoveisRouteChildren {
  AuthenticatedImoveisNovoRoute: typeof AuthenticatedImoveisNovoRoute
  AuthenticatedImoveisIndexRoute: typeof AuthenticatedImoveisIndexRoute
  AuthenticatedImoveisIdEditarRoute: typeof AuthenticatedImoveisIdEditarRoute
}

const AuthenticatedImoveisRouteChildren: AuthenticatedImoveisRouteChildren = {
  AuthenticatedImoveisNovoRoute: AuthenticatedImoveisNovoRoute,
  AuthenticatedImoveisIndexRoute: AuthenticatedImoveisIndexRoute,
  AuthenticatedImoveisIdEditarRoute: AuthenticatedImoveisIdEditarRoute,
}

const AuthenticatedImoveisRouteWithChildren =
  AuthenticatedImoveisRoute._addFileChildren(AuthenticatedImoveisRouteChildren)

interface AuthenticatedRegistrosIdRouteChildren {
  AuthenticatedRegistrosIdEditarRoute: typeof AuthenticatedRegistrosIdEditarRoute
}

const AuthenticatedRegistrosIdRouteChildren: AuthenticatedRegistrosIdRouteChildren =
  {
    AuthenticatedRegistrosIdEditarRoute: AuthenticatedRegistrosIdEditarRoute,
  }

const AuthenticatedRegistrosIdRouteWithChildren =
  AuthenticatedRegistrosIdRoute._addFileChildren(
    AuthenticatedRegistrosIdRouteChildren,
  )

interface AuthenticatedRegistrosRouteChildren {
  AuthenticatedRegistrosIdRoute: typeof AuthenticatedRegistrosIdRouteWithChildren
  AuthenticatedRegistrosNovoRoute: typeof AuthenticatedRegistrosNovoRoute
  AuthenticatedRegistrosIndexRoute: typeof AuthenticatedRegistrosIndexRoute
}

const AuthenticatedRegistrosRouteChildren: AuthenticatedRegistrosRouteChildren =
  {
    AuthenticatedRegistrosIdRoute: AuthenticatedRegistrosIdRouteWithChildren,
    AuthenticatedRegistrosNovoRoute: AuthenticatedRegistrosNovoRoute,
    AuthenticatedRegistrosIndexRoute: AuthenticatedRegistrosIndexRoute,
  }

const AuthenticatedRegistrosRouteWithChildren =
  AuthenticatedRegistrosRoute._addFileChildren(
    AuthenticatedRegistrosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCondominiosRoute: typeof AuthenticatedCondominiosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEdificiosRoute: typeof AuthenticatedEdificiosRoute
  AuthenticatedEmpreendimentosRoute: typeof AuthenticatedEmpreendimentosRoute
  AuthenticatedExportacoesRoute: typeof AuthenticatedExportacoesRoute
  AuthenticatedImobiliariasRoute: typeof AuthenticatedImobiliariasRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRegistrosRoute: typeof AuthenticatedRegistrosRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCondominiosRoute: AuthenticatedCondominiosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEdificiosRoute: AuthenticatedEdificiosRoute,
  AuthenticatedEmpreendimentosRoute: AuthenticatedEmpreendimentosRoute,
  AuthenticatedExportacoesRoute: AuthenticatedExportacoesRoute,
  AuthenticatedImobiliariasRoute: AuthenticatedImobiliariasRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRegistrosRoute: AuthenticatedRegistrosRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
